-- SCHEMA: tickfeed 

-- DROP SCHEMA IF EXISTS tickfeed;

CREATE SCHEMA IF NOT EXISTS tickfeed
    AUTHORIZATION user;

GRANT ALL ON SCHEMA tickfeed TO user;

CREATE ROLE tickfeedwriter WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  CONNECTION LIMIT 10

GRANT USAGE ON SCHEMA tickfeed TO tickfeedwriter;
